import { useEffect,useRef,useState } from 'react';import { Camera,CheckCircle2,Crosshair,ImagePlus,MapPin,Phone,Send,ShieldCheck,UploadCloud,X } from 'lucide-react';import toast from 'react-hot-toast';import { api,formatAgo,getPosition } from '../api';import { useData } from '../context/DataContext';import MapPanel from '../components/MapPanel';import { SectionTitle,SeverityBadge,StatusBadge } from '../components/UI';
const types=['Flooding','Fire','Road Blockage','Fallen Tree','Power Outage','Other'];
export default function Report(){const {incidents,refresh}=useData();const [form,setForm]=useState({type:'Flooding',description:'',contactNumber:''}),[position,setPosition]=useState({lat:26.8467,lng:80.9462}),[image,setImage]=useState(null),[preview,setPreview]=useState(''),[result,setResult]=useState(null),[submitting,setSubmitting]=useState(false);const fileRef=useRef();useEffect(()=>{getPosition().then(setPosition)},[]);function update(e){setForm({...form,[e.target.name]:e.target.value})}function choose(e){const f=e.target.files?.[0];if(!f)return;if(f.size>5*1024*1024)return toast.error('Image must be under 5 MB.');setImage(f);setPreview(URL.createObjectURL(f))}
 async function locate(){const p=await getPosition();setPosition(p);toast.success('Current location captured.')}
 async function submit(e){e.preventDefault();if(form.description.length<20)return toast.error('Please add at least 20 characters.');setSubmitting(true);try{const fd=new FormData();Object.entries(form).forEach(([k,v])=>fd.append(k,v));fd.append('location',JSON.stringify({...position,address:'Pinned location, Lucknow'}));if(image)fd.append('image',image);const {data}=await api.post('/incidents',fd);setResult(data.aiAnalysis);toast.success('Report submitted. Authorities notified.');setForm({type:'Flooding',description:'',contactNumber:''});setImage(null);setPreview('');await refresh()}catch(e2){toast.error(e2.response?.data?.error||'Unable to submit report.')}finally{setSubmitting(false)}}
 return <div className="mx-auto max-w-[1400px] px-4 py-8 sm:px-6 lg:py-10"><header className="mb-8"><p className="eyebrow">Citizen reporting</p><h1 className="mt-2 text-3xl font-extrabold tracking-tight text-ink md:text-4xl">See something? Signal it.</h1><p className="mt-2 max-w-2xl text-sm leading-6 text-slate-500">Your report helps residents avoid danger and gives response teams a clearer picture. Never put yourself at risk to capture evidence.</p></header>
 <div className="grid gap-6 lg:grid-cols-[1fr_.9fr]"><form onSubmit={submit} className="card p-5 sm:p-7"><SectionTitle eyebrow="Report details" title="Tell us what happened"/><div className="grid gap-5 sm:grid-cols-2"><label className="text-xs font-bold text-slate-600">Incident type<select className="field mt-2" name="type" value={form.type} onChange={update}>{types.map(x=><option key={x}>{x}</option>)}</select></label><label className="text-xs font-bold text-slate-600">Contact number <span className="font-normal text-slate-400">(optional)</span><div className="relative mt-2"><Phone className="absolute left-3 top-3.5 text-slate-400" size={16}/><input className="field !pl-10" name="contactNumber" value={form.contactNumber} onChange={update} placeholder="+91 98765 43210"/></div></label></div>
 <label className="mt-5 block text-xs font-bold text-slate-600">Description <span className="float-right font-normal text-slate-400">{form.description.length}/500</span><textarea className="field mt-2 min-h-32 resize-none" maxLength={500} name="description" value={form.description} onChange={update} placeholder="Describe what you can see, how severe it appears, and whether access is blocked…"/></label>
 <div className="mt-5"><p className="text-xs font-bold text-slate-600">Photo <span className="font-normal text-slate-400">(optional, JPG/PNG up to 5 MB)</span></p>{preview?<div className="relative mt-2 h-44 overflow-hidden rounded-xl border"><img src={preview} className="h-full w-full object-cover"/><button type="button" onClick={()=>{setImage(null);setPreview('')}} className="absolute right-2 top-2 rounded-full bg-black/70 p-2 text-white"><X size={15}/></button></div>:<button type="button" onClick={()=>fileRef.current.click()} className="mt-2 flex h-32 w-full flex-col items-center justify-center rounded-xl border-2 border-dashed border-slate-200 text-slate-400 transition hover:border-teal-400 hover:text-teal-700"><UploadCloud/><b className="mt-2 text-xs">Choose an image</b><span className="mt-1 text-[10px]">AI will assess visible hazards</span></button>}<input ref={fileRef} onChange={choose} type="file" accept="image/jpeg,image/png" hidden/></div>
 <button disabled={submitting} className="btn-primary mt-6 w-full !py-3.5"><Send size={17}/>{submitting?'Submitting and analysing…':'Submit report'}</button>{result&&<div className="mt-5 rounded-2xl border border-teal-200 bg-teal-50/60 p-5"><div className="flex items-center gap-2 text-teal-800"><CheckCircle2 size={18}/><b className="text-sm">AI image assessment</b></div><dl className="mt-4 grid gap-3 text-xs sm:grid-cols-2"><div><dt className="text-slate-500">Detected</dt><dd className="mt-1 font-bold text-ink">{result.detected}</dd></div><div><dt className="text-slate-500">Severity</dt><dd className="mt-1"><SeverityBadge level={result.severity}/></dd></div><div className="sm:col-span-2"><dt className="text-slate-500">Suggested action</dt><dd className="mt-1 leading-5 text-slate-700">{result.suggested_action}</dd></div></dl></div>}</form>
 <div className="space-y-6"><div className="card overflow-hidden"><div className="p-5"><div className="flex items-center justify-between"><div><p className="eyebrow">Pinpoint location</p><h2 className="mt-2 text-xl font-extrabold text-ink">Where is it?</h2></div><button type="button" onClick={locate} className="btn-ghost !py-2"><Crosshair size={15}/> Use my location</button></div><div className="mt-4 flex items-center gap-2 rounded-xl bg-slate-50 p-3 text-xs text-slate-600"><MapPin size={16} className="text-red-500"/><span>{position.lat.toFixed(5)}, {position.lng.toFixed(5)}</span></div></div><MapPanel height={380} pickable position={position} onPick={setPosition}/></div><div className="card flex gap-4 p-5"><span className="grid h-11 w-11 shrink-0 place-items-center rounded-xl bg-teal-50 text-teal-700"><ShieldCheck/></span><div><b className="text-sm text-ink">Your privacy matters</b><p className="mt-1 text-xs leading-5 text-slate-500">Contact details are only visible to response coordinators and are never shown on the public map.</p></div></div></div></div>
 <section className="card mt-7 overflow-hidden"><div className="p-5 sm:p-6"><SectionTitle eyebrow="Community feed" title="Recent reports"/></div><div className="overflow-x-auto"><table className="w-full min-w-[760px] text-left text-xs"><thead className="border-y bg-slate-50 text-[10px] uppercase tracking-wider text-slate-500"><tr>{['Type','Location','Severity','Time','Status'].map(x=><th key={x} className="px-6 py-3">{x}</th>)}</tr></thead><tbody className="divide-y">{incidents.slice(0,10).map(i=><tr key={i._id} className="hover:bg-slate-50"><td className="px-6 py-4 font-bold text-ink">{i.type}</td><td className="px-6 py-4 text-slate-500">{i.location.address}</td><td className="px-6 py-4"><SeverityBadge level={i.aiAnalysis?.severity}/></td><td className="px-6 py-4 text-slate-500">{formatAgo(i.createdAt)}</td><td className="px-6 py-4"><StatusBadge status={i.status}/></td></tr>)}</tbody></table></div></section>
 </div>}

