import { useState } from 'react';import { NavLink } from 'react-router-dom';import { AlertOctagon,Bot,ChartNoAxesCombined,FileWarning,LayoutDashboard,Menu,ShieldCheck,X } from 'lucide-react';import toast from 'react-hot-toast';import { api,getPosition } from '../api';
const links=[['/dashboard','Overview',LayoutDashboard],['/chat','Ask ResQAI',Bot],['/report','Report',FileWarning],['/admin','Command',ChartNoAxesCombined]];
export default function Navbar(){const [open,setOpen]=useState(false),[sos,setSos]=useState(false),[sending,setSending]=useState(false);async function sendSOS(){setSending(true);try{const p=await getPosition();await api.post('/incidents',{type:'SOS',description:'Emergency SOS triggered by user',lat:p.lat,lng:p.lng,severity:'High'});toast.success('SOS sent. Authorities alerted.',{duration:5000});setSos(false)}catch{toast.error('Unable to send SOS. Call 112 now.')}finally{setSending(false)}}return <>
 <nav className="sticky top-0 z-40 border-b border-white/10 bg-ink text-white"><div className="mx-auto flex h-[72px] max-w-[1500px] items-center px-4 sm:px-6"><NavLink to="/dashboard" className="mr-8 flex items-center gap-3"><span className="grid h-9 w-9 place-items-center rounded-xl bg-red-500"><ShieldCheck size={21}/></span><span><b className="block text-lg leading-none">ResQ<span className="text-red-400">AI</span></b><small className="text-[9px] font-bold uppercase tracking-[.2em] text-slate-400">Predict · Prepare · Protect</small></span></NavLink>
 <div className="hidden items-center gap-1 lg:flex">{links.map(([to,label,Icon])=><NavLink key={to} to={to} className={({isActive})=>`flex items-center gap-2 rounded-lg px-3 py-2 text-sm font-semibold transition ${isActive?'bg-white/10 text-white':'text-slate-400 hover:text-white'}`}><Icon size={16}/>{label}</NavLink>)}</div>
 <div className="ml-auto flex items-center gap-3"><span className="hidden items-center gap-2 text-xs font-semibold text-emerald-300 sm:flex"><i className="h-2 w-2 rounded-full bg-emerald-400 shadow-[0_0_10px_#34d399]"/> Systems operational</span><button onClick={()=>setSos(true)} className="flex items-center gap-2 rounded-xl bg-red-500 px-4 py-2.5 text-sm font-extrabold shadow-[0_8px_24px_rgba(239,68,68,.3)] hover:bg-red-600"><AlertOctagon size={17}/> SOS</button><button className="lg:hidden" onClick={()=>setOpen(!open)}>{open?<X/>:<Menu/>}</button></div></div>
 {open&&<div className="border-t border-white/10 px-4 py-3 lg:hidden">{links.map(([to,label,Icon])=><NavLink onClick={()=>setOpen(false)} key={to} to={to} className="flex items-center gap-3 rounded-lg px-3 py-3 text-sm text-slate-300"><Icon size={17}/>{label}</NavLink>)}</div>}</nav>
 {sos&&<div className="fixed inset-0 z-50 grid place-items-center bg-slate-950/70 p-4 backdrop-blur-sm"><div className="w-full max-w-md rounded-3xl bg-white p-7 text-center shadow-2xl"><span className="mx-auto grid h-16 w-16 place-items-center rounded-full bg-red-50 text-red-500"><AlertOctagon size={34}/></span><h2 className="mt-5 text-2xl font-extrabold text-ink">Send emergency alert?</h2><p className="mt-2 text-sm leading-6 text-slate-600">Your live location will be shared with the response desk. If you are in immediate danger, call <b>112</b>.</p><div className="mt-6 grid grid-cols-2 gap-3"><button className="btn-ghost" onClick={()=>setSos(false)}>Cancel</button><button disabled={sending} onClick={sendSOS} className="btn-primary !bg-red-500">{sending?'Sending…':'Confirm SOS'}</button></div></div></div>}</>}

